### ISSUE TITLE
Incompatible with Clifftree mod

### ISSUE THREAD

**Issue by littlelakehouse** [krypt0graphy/New-World-NeoForge#2]
Stuck at 0% when creating world 

World loads properly again when Newworld or Clifftree is removed

**Comment by krypt0graphy** [comment]
Post your latest.log

**Comment by krypt0graphy** [comment]
If it's on fabric, open the issue on https://github.com/ArshiaDPG/New-World-Fabric

I tested on NeoForge and they work

**Comment by krypt0graphy** [comment]
Try using this as a temporary solution https://modrinth.com/mod/feature-recycler
